### ISSUE TITLE
Doesn't work in perl 5.14.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [joyrex2001/protobuf-perlxs#9]
```
What steps will reproduce the problem?

Installed for perl 5.14.1, trying example 'big':
 perl Makefile.PL - ok
 make - ok
 make test - error:

Not a CODE reference at 
/usr/local/lib/perl5/5.14.1/i686-linux-thread-multi/DynaLoader.pm line 213.
END failed--call queue aborted at blib/lib/Big/Message.pm line 213.
Compilation failed in require at test.pl line 9.
BEGIN failed--compilation aborted at test.pl line 9.

But with ubuntu's perl 5.10.1 works good:

0.017285 seconds to set 10 blob fields
0.019572 seconds to pack message of 20971570 bytes
0.022064 seconds to unpack packed message
0.045516 seconds to freeze message of 20971600 bytes
0.029589 seconds to thaw frozen hashref



What version of the product are you using? On what operating system?

Ubuntu 11.04, perl 5.14.1 (self-built).




```

Original issue reported on code.google.com by `xlio...@gmail.com` on 3 Aug 2011 at 10:49
